name: update Model Repository

on: 
  repository_dispatch:
    types:
      - update

jobs:
#copies and replaces the updated models of the repository which triggered this action
  update-models:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the repo that triggered this workflow
       uses: actions/checkout@v4
       with:
          repository: ${{ github.event.client_payload.repo }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ secrets.TEST_REMOTE_CONTROLE }}  # needs read access to source repo
     - name: Confirm what we checked out
       run: |
           echo "Repo: ${{ github.event.client_payload.repo }}"
           echo "SHA:  ${{ github.event.client_payload.sha }}"
           echo "Ref:  ${{ github.event.client_payload.ref }}"
           echo "Add:  ${{ github.event.client_payload.add }}"
           echo "Modify:  ${{ github.event.client_payload.modify }}"
           echo "Delete:  ${{ github.event.client_payload.delete }}"
           git log --oneline -5
